### ISSUE TITLE
Security settings need update

### ISSUE THREAD

**Issue by fotinidelig** [lykmast/open-source-mondel#1]
To whom it may concern,

I found a security breach while running your app in a day-to-day fashion. Specifically, my personal data seem to be distributed to third-party-people without my permission. It's a bug not a feature!
Call for urgent update and fix of your security issues.
Privacy is freedom.

**Comment by lykmast** [comment]
Steps to reproduce, or it didn't happen.

**Comment by fotinidelig** [comment]
Show me your code or you're not open source.

**Comment by lykmast** [comment]
I have addressed this issue on its latest count of "not having any code" by pushing **THE ENTIRE PROJECT** in the latest commit. Evidence of security breaches still fails to emerge. As showcased by [this line](https://github.com/lykmast/open-source-mondel/blob/6424ebf61619b568c4cebe60bc7c3b4287707865/src/Lib.hs#L6), the project (or mondel if you will) has become officially open source.
